require('plugins')
require('core.colortheme')
require('core.options')
require('core.keymaps')
require('plugins.treesitter')
require('plugins.lspconfig')
require('plugins.autocomplete')
require('plugins.tex')
require('plugins.bufferline')
--require("flutter-tools").setup{} -- use defaults
--require('plugins.indentblankline')
require('plugins.telescope')
